
CREATE DATABASE IF NOT EXISTS price CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE price;

CREATE TABLE history_price
(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    date INT(16) UNSIGNED DEFAULT 0,
    ticket VARCHAR(20) NOT NULL,
    price VARCHAR(20) DEFAULT NULL
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO history_price(date, ticket, price) VALUES (1733560065, 'LCTUSDT', '137.33000000')
